### ISSUE TITLE
Quiz for search and replace...

### ISSUE THREAD

**Issue by kotp** [jordanhudgens/vim-settings#2]
Both `:s/pattern/replacement pattern` and `:%s/pattern/replacement pattern` will work, they just work differently.  Perhaps the question should be reworded?

![selection_001](https://cloud.githubusercontent.com/assets/16747/21336537/215611d0-c634-11e6-87f8-2fb958f8ad10.png)

**Comment by jordanhudgens** [comment]
Great point, I've updated it to say `all instances of a pattern` and I gave an example. Thanks for the feedback!

**Comment by kotp** [comment]
Remember that all instances of a pattern will happen with this: `:%s/pattern/other/g` where the g states "not just the first pattern per line".  The `%` representing the buffer, without it the search is valid only for that line.  Without the `g` at the end, only the first on the line will be replaced.

**Comment by jordanhudgens** [comment]
Good point, full universal does need that.
