### ISSUE TITLE
The "normal" mode of vim is called...

### ISSUE THREAD

**Issue by kotp** [jordanhudgens/vim-settings#3]
Normal mode, I think.  It could also be navigation mode.

![selection_002](https://cloud.githubusercontent.com/assets/16747/21338707/a35dcbca-c646-11e6-9ee5-80ed64af0b5d.png)

Vimtutor refers to it as "Normal mode" in:

> NOTE: If you are ever unsure about something you typed, press \<ESC\> to place
      you in Normal mode.  Then retype the command you wanted.

**Comment by jordanhudgens** [comment]
Updated.
